#############################################################################
# Makefile for building: qtpropertybrowser
# Generated by qmake (3.1) (Qt 5.14.1)
# Project:  qtpropertybrowser.pro
# Template: subdirs
# Command: D:\Qt\Qt_5.14.1\5.14.1\mingw73_64\bin\qmake.exe -o Makefile qtpropertybrowser.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: make_first
QMAKE         = D:\Qt\Qt_5.14.1\5.14.1\mingw73_64\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt_5.14.1\5.14.1\mingw73_64\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt_5.14.1\5.14.1\mingw73_64\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
IDC           = idc
IDL           = midl
ZIP           = zip -r -9
DEF_FILE      = 
RES_FILE      = 
SED           = $(QMAKE) -install sed
MOVE          = move
SUBTARGETS    =  \
		sub-examples


sub-examples-qmake_all:  FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
	cd examples\ && $(MAKE) -f Makefile qmake_all
sub-examples: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile
sub-examples-make_first-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-examples-make_first: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile 
sub-examples-all-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-examples-all: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile all
sub-examples-clean-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-examples-clean: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile clean
sub-examples-distclean-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-examples-distclean: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile distclean
sub-examples-install_subtargets-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-examples-install_subtargets: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile install
sub-examples-uninstall_subtargets-ordered: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall
sub-examples-uninstall_subtargets: FORCE
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile uninstall

Makefile: qtpropertybrowser.pro ../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/win32-g++/qmake.conf ../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/spec_pre.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/qdevice.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/device_config.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/sanitize.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/gcc-base.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/g++-base.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/angle.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/windows-vulkan.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/g++-win32.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/windows-desktop.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/qconfig.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_charts.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_script.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qt_functions.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qt_config.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/win32-g++/qmake.conf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/toolchain.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/default_pre.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/default_pre.prf \
		common.pri \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/resolve_config.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/default_post.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qml_debug.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/precompile_header.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/warn_on.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qmake_use.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/file_copies.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/windows.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/exceptions.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/yacc.prf \
		../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/lex.prf \
		qtpropertybrowser.pro
	$(QMAKE) -o Makefile qtpropertybrowser.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/spec_pre.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/qdevice.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/device_config.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/sanitize.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/gcc-base.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/g++-base.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/angle.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/windows_vulkan_sdk.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/windows-vulkan.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/g++-win32.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/common/windows-desktop.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/qconfig.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axbase.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axbase_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axcontainer_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axserver.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_axserver_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bodymovin_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_charts.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3d.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3d_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3drender.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3drender_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dutils.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick3dutils_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_script.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_script_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_vulkan_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_winextras.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_winextras_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qt_functions.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qt_config.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/win32-g++/qmake.conf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/toolchain.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/default_pre.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/default_pre.prf:
common.pri:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/resolve_config.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/default_post.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qml_debug.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/precompile_header.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/warn_on.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/qmake_use.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/file_copies.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/win32/windows.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/testcase_targets.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/exceptions.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/yacc.prf:
../../../../Qt_5.14.1/5.14.1/mingw73_64/mkspecs/features/lex.prf:
qtpropertybrowser.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile qtpropertybrowser.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug"

qmake_all: sub-examples-qmake_all FORCE

make_first: sub-examples-make_first-ordered  FORCE
all: sub-examples-all-ordered  FORCE
clean: sub-examples-clean-ordered  FORCE
distclean: sub-examples-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-examples-install_subtargets-ordered FORCE
uninstall_subtargets: sub-examples-uninstall_subtargets-ordered FORCE

sub-examples-check_ordered:
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile check
check: sub-examples-check_ordered

sub-examples-benchmark_ordered:
	@if not exist examples\ mkdir examples\ & if not exist examples\ exit 1
	cd examples\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Qt\haiTuProject\QtProperty\qtProperty_5\QtProperty\examples\examples.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" ) && $(MAKE) -f Makefile benchmark
benchmark: sub-examples-benchmark_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

